theme = 'npq-hugo'
baseURL = "/"
languageCode = "en-us"
title = "Austria Community & Meetups"
copyright = "Deployed with ❤️ on OpenShift - hosted and powered by CANCOM Plattform Services"
pygmentsUseClasses=true

[markup.goldmark.renderer]
unsafe= true

[params]
  author = "Shadowman"
  description = "overview of all events of redhat austria"
  keywords = "redhat austria events"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayHomeContent = true
  displayRecent = false
  recentMax = 4
  mail = "david.hanacek@redhat.com"

[menu]
  [[menu.main]]
    name = "Events"
    pre = "<i class=\"fas fa-calendar fa-sm\"></i>"
    url = "/"
    weight = -9
  [[menu.main]]
    name = "Red Hat Team"
    pre = "<i class=\"fas fa-address-book fa-ms\"></i>"
    url = "/team/"
    weight = -8
  [[menu.main]]
    name = "2026 Archiv"
    pre = "<i class=\"fas fa-archive fa-ms\"></i>"
    url = "/2026-archiv/"
    weight = -7
  [[menu.main]]
    name = "2025 Archiv"
    pre = "<i class=\"fas fa-archive fa-ms\"></i>"
    url = "/2025-archiv/"
    weight = -6
  [[menu.main]]
    name = "2024 Archiv"
    pre = "<i class=\"fas fa-archive fa-ms\"></i>"
    url = "/2024-archiv/"
    weight = -5
